Parse missing XPath-related features
bwrrp/xspattern.js pull request #13
Opened 2020-01-27 13:53 UTC by DrRataplan

Throw errors for now, but make the errors 'not implemented' errors instead of parsing errors.

TODO: Tests

2020-02-12 10:29 UTC, DrRataplan commented on src/parser.ts
> +	const backReference: Parser<any> = map(
TODO: Parser<number>

2020-02-17 15:48 UTC, DrRataplan commented
I added the tests. @bwrrp could you give this a look?

2020-03-04 10:52 UTC, bwrrp requested changes
This is great, thanks! I've left a few comments on minor nits.

2020-03-04 10:52 UTC, bwrrp commented on src/parser.ts
> +					restDigits.reduce((sum, digit) => sum * 10 + digit, firstDigit);
Creative! As an alternative, you could use the `recognize` combinator (and isDigit from below), with something like:
```
const backReferenceNumber: Parser<number> = map(
    recognize(
        preceded(
            filter(codepoint, charRangePredicate(asCodepoint('1'), asCodepoint('9')), ['digit']),
            star(filter(codepoint, isDigit, ['digit']))
        )
    ),
    str => parseInt(str, 10)
);
```

2020-03-04 10:52 UTC, bwrrp commented on src/sets.ts
> +	INPUT_END_SENTINAL,
spelling nit: sentinel
(same for other occurrences below)

2020-03-04 10:52 UTC, bwrrp commented on test/xspattern.tests.ts
> +describe.only('xspattern', () => {
leftover from testing?

2020-03-04 10:52 UTC, bwrrp commented on test/xspattern.tests.ts
> +	it('throws the correct error when it sees backreferences', () => {
Could you also add a few tests that show that XPath-specific syntax such as backreferences throws appropriate parsing errors (or may be interpreted as a different type of expression) in XSD mode?

2020-03-13 08:48 UTC, merged